name: My First Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v4

      - name: Print a message
        run: echo "Hello from GitHub Actions!"

      - name: Show current date
        run: date

      - name: List files in repo
        run: ls -la